### ISSUE TITLE
QR code to $GET url

### ISSUE THREAD

**Issue by b-gauthier** [code-kotis/barcode-scanner#23]
Hi, 

What i would like to do is to directly follow an url after scannig a qrcode : 

ex : https://www.mydomain.com/page.html?qrcode=codejustscanned

What kind of changes I have to do in your script to do that ? 

Thank you very much,

**Comment by gokulkrishh** [comment]
Hi @batgau71,

you will get the result in [main.js](https://github.com/code-kotis/barcode-scanner/blob/master/app/js/main.js#L68) line no 68. All you have to do is open your desired url using `window.open` with scanned code.

Hope this answers your question. Thanks

**Comment by b-gauthier** [comment]
Perfect ! Thank you ! ;)

**Comment by gokulkrishh** [comment]
@batgau71 Cool 👍

**Comment by ghost** [comment]
Hi @gokulkrishh. Thank you for making this wonderful program. This is one of the best working solution on the internet for QR scanning using browser.
Could you please help me to understand what changes do I make in the web version (gh-pages) main.201113f887d44acdfa77.bundle.js file to redirect to the scanned URL, instead of showing the popup/snackbar.

**Comment by gokulkrishh** [comment]
@hvarora Thanks. 

Source: https://github.com/code-kotis/qr-code-scanner/blob/master/app/js/main.js#L92

In above line, scan method we get the result. There you have to do changes required to open or redirect the result if its URL.

You have edit the source and build the app to make it work.  

And `main.201113f887d44acdfa77.bundle.js` is compiled & minified version to make changes in this file would be hard to find and do it.
