### ISSUE TITLE
QR code scanning not working  after adding to home screen

### ISSUE THREAD

**Issue by anujaverma** [code-kotis/barcode-scanner#74]
I loaded the website qrcodescan.in in safari browser on iphone and the scanner worked perfectly. I then added the website to home screen. Now when I clicked on the icon on my home screen, the app opened up but the camera did not load. There was a button in the bottom that I used to open the camera but the camera did not end up scanning the QR code

Is scanning not supposed to work from home screen of iphone?

Software version of IOS is 12.4.1

**Comment by gokulkrishh** [comment]
@anujaverma Hi, Yes issue is there even in iOS 13 because when you add to home screen its not longer safari instance of the browser but its a webkit webview from safari. Which doesn't have access to the camera API/ Hence we add a button to capture a pic and then use it for scanning.

So take a picture using the camera via the button and select use photo for scanning.

Closing this issue as its current behaviour due to restring from Apple. Feel free to re-open if needed
